name="Fan-Fail Test Test"
pass="Fan-Fail Test successfully completed"
fail="Fan-Fail Test failed"
retryCount=0

[step:1]
msg="Turn on FG 1 | "
waitFor="fanLevel1Running;fanLevel2Running;fanLevel3Running;fanLevel4Running;fan1Status;fan2Status;fan3Status;fan4Status;fan5Status;fan6Status"
waitTime=15
expectedValue="true;false;false;false;1;1;0;0;0;0"
onPass="Fan 1 & 2 is On"
onFail="Fan 1 & 2 not started"

[step:2]
msg="Remove Fan 1 Wire"
waitFor="fanLevel1Running;fanLevel2Running;fanLevel3Running;fanLevel4Running;fan1Status;fan2Status;fan3Status;fan4Status;fan5Status;fan6Status"
waitTime=20
expectedValue="true;false;false;false;2;1;0;0;0;0"
onPass="Fan 1 Wire removed successfully"
onFail="Fan 1 wire not removed"
