name="Fire Alarm Test"
pass="Fire Alarm Test successfully completed"
fail="Fire Alarm Test failed"
retryCount=0

[step:1]
msg="No Fire alarm should not appear now"
waitFor="fireAlarm"
waitTime=10
expectedValue="0"
onPass="Fire alarm is off, ready to test"
onFail="Fire Alarm already ON"

[step:2]
msg="Start testing Fire Alarm"
waitFor="fireAlarm"
waitTime=10
expectedValue="1"
onPass="Fire alarm turned on successfully"
onFail="Fire Alarm not turned on"

[step:3]
msg="Remove Fire from near sensor"
waitFor="fireAlarm"
waitTime=10
expectedValue="0"
onPass="Fire alarm turned off successfully"
onFail="Fire alarm not turned off"

