name="EM Lock through Keypad"
pass="EM Lock tested successfully"
fail="Lock test Test failed"
retryCount=0

[step:1]
msg="Door should be locked"
waitFor="lockStatus"
waitTime=10
expectedValue="CLOSED"
onPass="Lock is ready to test"
onFail="Door is already open"

[step:2]
msg="Enter password through Keypad to open Lock"
waitFor="lockStatus"
waitTime=10
expectedValue="OPEN"
onPass="Door opened successfully"
onFail="Door not opened"

[step:3]
msg="Wait for closing the door"
waitFor="lockStatus"
waitTime=10
expectedValue="CLOSED"
onPass="Door closed successfully"
onFail="Door not closed"

