name="Outside Temperature Test"
type="sensor"
pass="Outside Temperature successfully completed"
fail="Outside Temperature Test failed"
retryCount=0

[step:1]
type="instruction"
msg="Prepare Heat Gun"
waitTime=4
onPass="Heat gun ready."

[step:2]
msg="Outside Temperature Sensor test started"
waitFor="outsideTemperature"
waitTime=25
increasedBy=5
onPass="Outside Temperature alarm successfully"
onFail="Outside Temperature alarm not turned on"
