name="Inside Temperature Test"
type="sensor"
pass="Inside Temperature test successfully completed"
fail="Inside Temperature Test failed"
retryCount=0

[step:1]
msg="Inside Temperature Sensor test started"
waitFor="insideTemperature"
waitTime=25
increasedBy=5
onPass="Inside Temperature sensor successfully tested"
onFail="Inside Temperature not increased by 5°C"
